import catalog from "./assets/companies-logos/Catalog.png";
import circooles from "./assets/companies-logos/Circooles.png";
import commandr from "./assets/companies-logos/Command+R.png";
import hourglass from "./assets/companies-logos/Hourglass.png";
import layers from "./assets/companies-logos/Layers.png";
import quotient from "./assets/companies-logos/Quotient.png";
import sisyphus from "./assets/companies-logos/Sisyphus.png";

import avatar1 from "./assets/avatars-small/Avatar-1.png";
import avatar2 from "./assets/avatars-small/Avatar-2.png";
import avatar3 from "./assets/avatars-small/Avatar-3.png";
import avatar4 from "./assets/avatars-small/Avatar-4.png";
import avatar5 from "./assets/avatars-small/Avatar-5.png";

export const data = [
  {
    name: "Circooles",
    website: "getcirooles.com",
    logo: circooles,
    status: "Churned",
    about: "Design software",
    aboutDesc: "Super lightweight design app",
    users: [avatar3, avatar1, avatar4, avatar2, avatar5],
    undisplayedUsers: 8,
    progress: "60%",
  },
  {
    name: "Hourglass",
    website: "hourglass.app",
    logo: hourglass,
    status: "Customer",
    about: "Productivity app",
    aboutDesc: "Time management and productivity",
    users: [avatar1, avatar2, avatar3, avatar5, avatar4],
    undisplayedUsers: 0,
    progress: "85%",
  },
  {
    name: "Layers",
    website: "getlayers.io",
    logo: layers,
    status: "Churned",
    about: "Web app integrations",
    aboutDesc: "Connect web apps seamlessly",
    users: [avatar4, avatar3, avatar2, avatar5, avatar1],
    undisplayedUsers: 1,
    progress: "30%",
  },
  {
    name: "Command+R",
    website: "cmdr.ai",
    logo: commandr,
    status: "Customer",
    about: "Data prediction",
    aboutDesc: "AI and machine learning data",
    users: [avatar4, avatar3, avatar5, avatar1, avatar2],
    undisplayedUsers: 2,
    progress: "40%",
  },
  {
    name: "Quotient",
    website: "quotient.co",
    logo: quotient,
    status: "Customer",
    about: "Sales CRM",
    aboutDesc: "Web-based sales doc management",
    users: [avatar4, avatar3, avatar2, avatar5, avatar1],
    undisplayedUsers: 6,
    progress: "20%",
  },
  {
    name: "Sisyphus",
    website: "sisyphus.com",
    logo: sisyphus,
    status: "Customer",
    about: "Automation and workflow",
    aboutDesc: "Time tracking, invoicing and expenses",
    users: [avatar1, avatar2, avatar3, avatar5, avatar4],
    undisplayedUsers: 4,
    progress: "40%",
  },
  {
    name: "Circooles",
    website: "getcirooles.com",
    logo: circooles,
    status: "Churned",
    about: "Design software",
    aboutDesc: "Super lightweight design app",
    users: [avatar3, avatar1, avatar4, avatar2, avatar5],
    undisplayedUsers: 8,
    progress: "60%",
  },
  {
    name: "Layers",
    website: "getlayers.io",
    logo: layers,
    status: "Churned",
    about: "Web app integrations",
    aboutDesc: "Connect web apps seamlessly",
    users: [avatar4, avatar3, avatar2, avatar5, avatar1],
    undisplayedUsers: 1,
    progress: "30%",
  },
  {
    name: "Catalog",
    website: "catalogapp.io",
    logo: catalog,
    status: "Customer",
    about: "Content curating app",
    aboutDesc: "Brings all your news into one place",
    users: [avatar1, avatar2, avatar3, avatar5, avatar4],
    undisplayedUsers: 5,
    progress: "70%",
  },
  {
    name: "Hourglass",
    website: "hourglass.app",
    logo: hourglass,
    status: "Customer",
    about: "Productivity app",
    aboutDesc: "Time management and productivity",
    users: [avatar1, avatar2, avatar3, avatar5, avatar4],
    undisplayedUsers: 0,
    progress: "85%",
  },
];

export const projectsData = [
  {
    name: "Design software",
    description: "Super lightweight design app",
    teamMembers: [avatar3, avatar1, avatar4, avatar2, avatar5],
    website: "getcirooles.com",
    logo: circooles,
    undisplayedUsers: 8,
    status: "Active",
    dueDate: "12.03.2023",
  },
  {
    name: "Productivity app",
    description: "Time management and productivity",
    teamMembers: [avatar1, avatar2, avatar3, avatar5, avatar4],
    website: "hourglass.app",
    logo: hourglass,
    undisplayedUsers: 0,
    status: "Upcoming",
    dueDate: "20.03.2023",
  },
  {
    name: "Web app integrations",
    description: "Connect web apps seamlessly",
    teamMembers: [avatar4, avatar3, avatar2, avatar5, avatar1],
    website: "getlayers.io",
    logo: layers,
    undisplayedUsers: 5,
    status: "Active",
    dueDate: "01.04.2023",
  },
  {
    name: "Data prediction",
    description: "AI and machine learning data",
    teamMembers: [avatar4, avatar3, avatar5, avatar1, avatar2],
    website: "cmdr.ai",
    logo: commandr,
    undisplayedUsers: 2,
    status: "Active",
    dueDate: "12.04.2023",
  },
  {
    name: "Sales CRM",
    description: "Web-based sales doc management",
    teamMembers: [avatar4, avatar3, avatar2, avatar5, avatar1],
    website: "quotient.co",
    logo: quotient,
    undisplayedUsers: 6,
    status: "Active",
    dueDate: "20.04.2023",
  },
  {
    name: "Automation and workflow",
    description: "Time tracking, invoicing and expenses",
    teamMembers: [avatar1, avatar2, avatar3, avatar5, avatar4],
    website: "sisyphus.com",
    logo: sisyphus,
    undisplayedUsers: 4,
    status: "Upcoming",
    dueDate: "20.04.2023",
  },
  {
    name: "Web app integrations",
    description: "Connect web apps seamlessly",
    teamMembers: [avatar4, avatar3, avatar2, avatar5, avatar1],
    website: "getlayers.io",
    logo: layers,
    undisplayedUsers: 5,
    status: "Active",
    dueDate: "01.04.2023",
  },
  {
    name: "Sales CRM",
    description: "Web-based sales doc management",
    teamMembers: [avatar4, avatar3, avatar2, avatar5, avatar1],
    website: "quotient.co",
    logo: quotient,
    undisplayedUsers: 6,
    status: "Active",
    dueDate: "20.04.2023",
  },
  {
    name: "Data prediction",
    description: "AI and machine learning data",
    teamMembers: [avatar4, avatar3, avatar5, avatar1, avatar2],
    website: "cmdr.ai",
    logo: commandr,
    undisplayedUsers: 2,
    status: "Active",
    dueDate: "12.04.2023",
  },
];
